### ISSUE TITLE
auth_token / API_KEY confusion

### ISSUE THREAD

**Issue by tripodsan** [hlxsites/tmg-ucm#10]
it looks like the `auth_token` header https://github.com/hlxsites/tmg-ucm/blob/0d7a93edec6ea22d4bc8fd3b28154e1fd61fd152/worker/routes/content/index.ts#L44 is needs to be equal to the ucm `API_KEY`... which is the worst of both worlds :-)

- a) either, the ucm api-key is configured in the worker, and an additional password/shared-key is used to authenticate the entire worker,
- b) or, the API_KEY is transparently used for the ucm access, in this case the only authentication validation is done by the ucm api.

in any case, `auth_token` is IMO the wrong name.  IMO, a _token_ is a (temporary), automatically generated secret to access a resource (eg access token, refresh token). where was as a _key_ or a _password_ is generated by a human.

if we're doing (a), I would call it `proxy-key`. even better would be using the `Authorization` header. maybe with a type `Key`. eg:

```
Authorization: Key XXYYZZ
```

or, if it's a password, we can also name it basic auth :-)

```
Authorization: Basic XXYYZZ
```

(and maybe use `admin:password` )

/cc @davidnuescheler

**Comment by maxakuru** [comment]
@tripodsan 

I lean towards option (a), mostly because I think the worker should be opaque to Helix in terms of underlying auth/api requests. If someone provides access to an http endpoint and gives Helix access with a password/key/token, that shouldn't mean Helix also has access to anything else

`auth_token` header can be replaced with `authorization: key abc`, makes sense. Using `Authorization` header was the longer term plan, just put something in quickly that mimicked the cookie.
